package com.temenos.infinityassist.retail;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RetailRiskScoreParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String employmentStatus;

	private java.lang.Integer age;

	private java.lang.Integer bureauScore;

	private java.lang.Integer relationshipWithBank;

	public RetailRiskScoreParams() {
	}

	public java.lang.String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(java.lang.String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getBureauScore() {
		return this.bureauScore;
	}

	public void setBureauScore(java.lang.Integer bureauScore) {
		this.bureauScore = bureauScore;
	}

	public java.lang.Integer getRelationshipWithBank() {
		return this.relationshipWithBank;
	}

	public void setRelationshipWithBank(java.lang.Integer relationshipWithBank) {
		this.relationshipWithBank = relationshipWithBank;
	}

	public RetailRiskScoreParams(java.lang.String employmentStatus,
			java.lang.Integer age, java.lang.Integer bureauScore,
			java.lang.Integer relationshipWithBank) {
		this.employmentStatus = employmentStatus;
		this.age = age;
		this.bureauScore = bureauScore;
		this.relationshipWithBank = relationshipWithBank;
	}

}