package com.myspace.corporatelos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CorpQueueDMNInput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String taskName;

	private java.lang.String taskPriority;

	public CorpQueueDMNInput() {
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public java.lang.String getTaskPriority() {
		return this.taskPriority;
	}

	public void setTaskPriority(java.lang.String taskPriority) {
		this.taskPriority = taskPriority;
	}

	public CorpQueueDMNInput(java.lang.String taskName,
			java.lang.String taskPriority) {
		this.taskName = taskName;
		this.taskPriority = taskPriority;
	}

}