package com.temenos.infinityassist.sme.submitted;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PartyRelatedInformationParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String firstName;
	private java.lang.String lastName;
	private java.lang.String emailAddress;
	private java.lang.String countryCode;
	private java.lang.String phoneNumber;
	private java.lang.String role;
	private java.lang.String relationshipWithCompany;
	private java.lang.String percentageOfOwnership;

	private java.lang.String identityType;

	private java.lang.String issuedCountry;

	private java.lang.String issuedState;

	private java.lang.String issueDate;

	private java.lang.String expirationDate;

	private java.lang.String addressLine1;

	private java.lang.String addressLine2;

	private java.lang.String city;

	private java.lang.String state;

	private java.lang.String zipCode;

	private java.lang.String idNumber;

	public PartyRelatedInformationParams() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(java.lang.String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public java.lang.String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(java.lang.String countryCode) {
		this.countryCode = countryCode;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getRelationshipWithCompany() {
		return this.relationshipWithCompany;
	}

	public void setRelationshipWithCompany(
			java.lang.String relationshipWithCompany) {
		this.relationshipWithCompany = relationshipWithCompany;
	}

	public java.lang.String getPercentageOfOwnership() {
		return this.percentageOfOwnership;
	}

	public void setPercentageOfOwnership(java.lang.String percentageOfOwnership) {
		this.percentageOfOwnership = percentageOfOwnership;
	}

	public java.lang.String getIdentityType() {
		return this.identityType;
	}

	public void setIdentityType(java.lang.String identityType) {
		this.identityType = identityType;
	}

	public java.lang.String getIssuedCountry() {
		return this.issuedCountry;
	}

	public void setIssuedCountry(java.lang.String issuedCountry) {
		this.issuedCountry = issuedCountry;
	}

	public java.lang.String getIssuedState() {
		return this.issuedState;
	}

	public void setIssuedState(java.lang.String issuedState) {
		this.issuedState = issuedState;
	}

	public java.lang.String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(java.lang.String issueDate) {
		this.issueDate = issueDate;
	}

	public java.lang.String getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(java.lang.String expirationDate) {
		this.expirationDate = expirationDate;
	}

	public java.lang.String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(java.lang.String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public java.lang.String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(java.lang.String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.String zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(java.lang.String idNumber) {
		this.idNumber = idNumber;
	}

	public PartyRelatedInformationParams(java.lang.String firstName,
			java.lang.String lastName, java.lang.String emailAddress,
			java.lang.String countryCode, java.lang.String phoneNumber,
			java.lang.String role, java.lang.String relationshipWithCompany,
			java.lang.String percentageOfOwnership,
			java.lang.String identityType, java.lang.String issuedCountry,
			java.lang.String issuedState, java.lang.String issueDate,
			java.lang.String expirationDate, java.lang.String addressLine1,
			java.lang.String addressLine2, java.lang.String city,
			java.lang.String state, java.lang.String zipCode,
			java.lang.String idNumber) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.countryCode = countryCode;
		this.phoneNumber = phoneNumber;
		this.role = role;
		this.relationshipWithCompany = relationshipWithCompany;
		this.percentageOfOwnership = percentageOfOwnership;
		this.identityType = identityType;
		this.issuedCountry = issuedCountry;
		this.issuedState = issuedState;
		this.issueDate = issueDate;
		this.expirationDate = expirationDate;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.idNumber = idNumber;
	}

}