package com.temenos.infinityassist.sme.submitted;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PartyInformationParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String companyName;
	private java.lang.String companyType;
	private java.lang.String industryType;
	private java.lang.String subIndustryType;
	private java.lang.String countryOfIncorporation;
	private String yearsInBusiness;
	private java.lang.String registrationId;
	private java.lang.String registrationDate;
	private java.lang.String expiryDate;
	private java.lang.String taxId;
	private java.lang.String companyAddressLine1;
	private java.lang.String companyAddressLine2;
	private java.lang.String country;
	private java.lang.String state;
	private java.lang.String city;
	private java.lang.String zipCode;
	private java.lang.String countryCode;
	private java.lang.String phoneNumber;

	public PartyInformationParams() {
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}

	public java.lang.String getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(java.lang.String companyType) {
		this.companyType = companyType;
	}

	public java.lang.String getIndustryType() {
		return this.industryType;
	}

	public void setIndustryType(java.lang.String industryType) {
		this.industryType = industryType;
	}

	public java.lang.String getSubIndustryType() {
		return this.subIndustryType;
	}

	public void setSubIndustryType(java.lang.String subIndustryType) {
		this.subIndustryType = subIndustryType;
	}

	public java.lang.String getCountryOfIncorporation() {
		return this.countryOfIncorporation;
	}

	public void setCountryOfIncorporation(
			java.lang.String countryOfIncorporation) {
		this.countryOfIncorporation = countryOfIncorporation;
	}

	public java.lang.String getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(java.lang.String registrationId) {
		this.registrationId = registrationId;
	}

	public java.lang.String getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(java.lang.String registrationDate) {
		this.registrationDate = registrationDate;
	}

	public java.lang.String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(java.lang.String expiryDate) {
		this.expiryDate = expiryDate;
	}

	public java.lang.String getTaxId() {
		return this.taxId;
	}

	public void setTaxId(java.lang.String taxId) {
		this.taxId = taxId;
	}

	public java.lang.String getCompanyAddressLine1() {
		return this.companyAddressLine1;
	}

	public void setCompanyAddressLine1(java.lang.String companyAddressLine1) {
		this.companyAddressLine1 = companyAddressLine1;
	}

	public java.lang.String getCompanyAddressLine2() {
		return this.companyAddressLine2;
	}

	public void setCompanyAddressLine2(java.lang.String companyAddressLine2) {
		this.companyAddressLine2 = companyAddressLine2;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.String zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(java.lang.String countryCode) {
		this.countryCode = countryCode;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getYearsInBusiness() {
		return this.yearsInBusiness;
	}

	public void setYearsInBusiness(java.lang.String yearsInBusiness) {
		this.yearsInBusiness = yearsInBusiness;
	}

	public PartyInformationParams(java.lang.String companyName,
			java.lang.String companyType, java.lang.String industryType,
			java.lang.String subIndustryType,
			java.lang.String countryOfIncorporation,
			java.lang.String yearsInBusiness, java.lang.String registrationId,
			java.lang.String registrationDate, java.lang.String expiryDate,
			java.lang.String taxId, java.lang.String companyAddressLine1,
			java.lang.String companyAddressLine2, java.lang.String country,
			java.lang.String state, java.lang.String city,
			java.lang.String zipCode, java.lang.String countryCode,
			java.lang.String phoneNumber) {
		this.companyName = companyName;
		this.companyType = companyType;
		this.industryType = industryType;
		this.subIndustryType = subIndustryType;
		this.countryOfIncorporation = countryOfIncorporation;
		this.yearsInBusiness = yearsInBusiness;
		this.registrationId = registrationId;
		this.registrationDate = registrationDate;
		this.expiryDate = expiryDate;
		this.taxId = taxId;
		this.companyAddressLine1 = companyAddressLine1;
		this.companyAddressLine2 = companyAddressLine2;
		this.country = country;
		this.state = state;
		this.city = city;
		this.zipCode = zipCode;
		this.countryCode = countryCode;
		this.phoneNumber = phoneNumber;
	}

}