package com.myspace.corporatelos.offeracceptance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OfferAcceptanceScripts implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public OfferAcceptanceScripts() {
	}

	public static void checkSignedTermsSheet(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			org.json.JSONObject responseObj = new org.json.JSONObject(kcontext
					.getVariable("response").toString());
			org.json.JSONArray documents = responseObj
					.getJSONArray("documents");
			if (documents.length() > 0) {
				for (int i = 0; i < documents.length(); i++) {
					org.json.JSONObject indDocument = new org.json.JSONObject(
							documents.get(i).toString());
						if (indDocument.get("documentType").equals("trm_sht")
							&& indDocument.get("documentStatus").equals("05") && indDocument.get("documentCategory").equals("agrmnt_doc")) {
						kcontext.setVariable("result", true);
						break;
					} else {
						kcontext.setVariable("result", false);
					}
				}
			} else {
				kcontext.setVariable("result", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

}