package com.myspace.corporatelos.underwriting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class approvalMatrix implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String approver;
	private java.lang.String name;

	private java.lang.Integer priority;

	public approvalMatrix() {
	}

	public java.lang.String getApprover() {
		return this.approver;
	}

	public void setApprover(java.lang.String approver) {
		this.approver = approver;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public approvalMatrix(java.lang.String approver, java.lang.String name,
			java.lang.Integer priority) {
		this.approver = approver;
		this.name = name;
		this.priority = priority;
	}

}