package com.myspace.corporatelos.underwriting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DecisionParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer bureauScore;
	private java.lang.Integer bankRelationship;
	private java.lang.Integer yearsOfOperation;
	private java.lang.String managementAssessment;
	private Double tolRatio;
	private Double dscr;
	private java.lang.Integer salesTurnOverGrowth;
	private java.lang.Integer cashFlowOperation;
	private java.lang.Integer inwardChequeReturns;
	private java.lang.Integer creditSummation;

	public DecisionParams() {
	}

	public java.lang.Integer getBureauScore() {
		return this.bureauScore;
	}

	public void setBureauScore(java.lang.Integer bureauScore) {
		this.bureauScore = bureauScore;
	}

	public java.lang.Integer getBankRelationship() {
		return this.bankRelationship;
	}

	public void setBankRelationship(java.lang.Integer bankRelationship) {
		this.bankRelationship = bankRelationship;
	}

	public java.lang.Integer getYearsOfOperation() {
		return this.yearsOfOperation;
	}

	public void setYearsOfOperation(java.lang.Integer yearsOfOperation) {
		this.yearsOfOperation = yearsOfOperation;
	}

	public java.lang.String getManagementAssessment() {
		return this.managementAssessment;
	}

	public void setManagementAssessment(java.lang.String managementAssessment) {
		this.managementAssessment = managementAssessment;
	}

	public java.lang.Integer getSalesTurnOverGrowth() {
		return this.salesTurnOverGrowth;
	}

	public void setSalesTurnOverGrowth(java.lang.Integer salesTurnOverGrowth) {
		this.salesTurnOverGrowth = salesTurnOverGrowth;
	}

	public java.lang.Integer getCashFlowOperation() {
		return this.cashFlowOperation;
	}

	public void setCashFlowOperation(java.lang.Integer cashFlowOperation) {
		this.cashFlowOperation = cashFlowOperation;
	}

	public java.lang.Integer getInwardChequeReturns() {
		return this.inwardChequeReturns;
	}

	public void setInwardChequeReturns(java.lang.Integer inwardChequeReturns) {
		this.inwardChequeReturns = inwardChequeReturns;
	}

	public java.lang.Integer getCreditSummation() {
		return this.creditSummation;
	}

	public void setCreditSummation(java.lang.Integer creditSummation) {
		this.creditSummation = creditSummation;
	}

	public java.lang.Double getTolRatio() {
		return this.tolRatio;
	}

	public void setTolRatio(java.lang.Double tolRatio) {
		this.tolRatio = tolRatio;
	}

	public java.lang.Double getDscr() {
		return this.dscr;
	}

	public void setDscr(java.lang.Double dscr) {
		this.dscr = dscr;
	}

	public DecisionParams(java.lang.Integer bureauScore,
			java.lang.Integer bankRelationship,
			java.lang.Integer yearsOfOperation,
			java.lang.String managementAssessment, java.lang.Double tolRatio,
			java.lang.Double dscr, java.lang.Integer salesTurnOverGrowth,
			java.lang.Integer cashFlowOperation,
			java.lang.Integer inwardChequeReturns,
			java.lang.Integer creditSummation) {
		this.bureauScore = bureauScore;
		this.bankRelationship = bankRelationship;
		this.yearsOfOperation = yearsOfOperation;
		this.managementAssessment = managementAssessment;
		this.tolRatio = tolRatio;
		this.dscr = dscr;
		this.salesTurnOverGrowth = salesTurnOverGrowth;
		this.cashFlowOperation = cashFlowOperation;
		this.inwardChequeReturns = inwardChequeReturns;
		this.creditSummation = creditSummation;
	}

}