package com.temenos.infinityassist.retail.submitted;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductQueueInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String productGroup;
	private java.lang.Float loanAmount;

	public ProductQueueInfo() {
	}

	public java.lang.String getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(java.lang.String productGroup) {
		this.productGroup = productGroup;
	}

	public java.lang.Float getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(java.lang.Float loanAmount) {
		this.loanAmount = loanAmount;
	}

	public ProductQueueInfo(java.lang.String productGroup,
			java.lang.Float loanAmount) {
		this.productGroup = productGroup;
		this.loanAmount = loanAmount;
	}

}