package com.temenos.infinityassist.sme;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SMECreditScoreOutput implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer companyBureauScoreOutput;
	private java.lang.Integer partyBureauScoreOutput;
	private java.lang.Integer relationshipWithBankOutput;
	private java.lang.Integer yearsOfEmploymentOutput;
	private Integer managementAssessmentOutput;
	private Integer financialLeverageOutput;
	private Integer dSCROutput;
	private Integer operatingMarginOutput;
	private Integer netProfitMarginOutput;
	private java.lang.Integer totalScore;

	private java.lang.Integer currentRatioOutput;

	public SMECreditScoreOutput() {
	}

	public java.lang.Integer getCompanyBureauScoreOutput() {
		return this.companyBureauScoreOutput;
	}

	public void setCompanyBureauScoreOutput(
			java.lang.Integer companyBureauScoreOutput) {
		this.companyBureauScoreOutput = companyBureauScoreOutput;
	}

	public java.lang.Integer getPartyBureauScoreOutput() {
		return this.partyBureauScoreOutput;
	}

	public void setPartyBureauScoreOutput(
			java.lang.Integer partyBureauScoreOutput) {
		this.partyBureauScoreOutput = partyBureauScoreOutput;
	}

	public java.lang.Integer getRelationshipWithBankOutput() {
		return this.relationshipWithBankOutput;
	}

	public void setRelationshipWithBankOutput(
			java.lang.Integer relationshipWithBankOutput) {
		this.relationshipWithBankOutput = relationshipWithBankOutput;
	}

	public java.lang.Integer getYearsOfEmploymentOutput() {
		return this.yearsOfEmploymentOutput;
	}

	public void setYearsOfEmploymentOutput(
			java.lang.Integer yearsOfEmploymentOutput) {
		this.yearsOfEmploymentOutput = yearsOfEmploymentOutput;
	}

	public java.lang.Integer getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(java.lang.Integer totalScore) {
		this.totalScore = totalScore;
	}

	public java.lang.Integer getdSCROutput() {
		return this.dSCROutput;
	}

	public void setdSCROutput(java.lang.Integer dSCROutput) {
		this.dSCROutput = dSCROutput;
	}

	public java.lang.Integer getFinancialLeverageOutput() {
		return this.financialLeverageOutput;
	}

	public void setFinancialLeverageOutput(
			java.lang.Integer financialLeverageOutput) {
		this.financialLeverageOutput = financialLeverageOutput;
	}

	public java.lang.Integer getManagementAssessmentOutput() {
		return this.managementAssessmentOutput;
	}

	public void setManagementAssessmentOutput(
			java.lang.Integer managementAssessmentOutput) {
		this.managementAssessmentOutput = managementAssessmentOutput;
	}

	public java.lang.Integer getNetProfitMarginOutput() {
		return this.netProfitMarginOutput;
	}

	public void setNetProfitMarginOutput(java.lang.Integer netProfitMarginOutput) {
		this.netProfitMarginOutput = netProfitMarginOutput;
	}

	public java.lang.Integer getOperatingMarginOutput() {
		return this.operatingMarginOutput;
	}

	public void setOperatingMarginOutput(java.lang.Integer operatingMarginOutput) {
		this.operatingMarginOutput = operatingMarginOutput;
	}

	public java.lang.Integer getCurrentRatioOutput() {
		return this.currentRatioOutput;
	}

	public void setCurrentRatioOutput(java.lang.Integer currentRatioOutput) {
		this.currentRatioOutput = currentRatioOutput;
	}

	public SMECreditScoreOutput(java.lang.Integer companyBureauScoreOutput,
			java.lang.Integer partyBureauScoreOutput,
			java.lang.Integer relationshipWithBankOutput,
			java.lang.Integer yearsOfEmploymentOutput,
			java.lang.Integer managementAssessmentOutput,
			java.lang.Integer financialLeverageOutput,
			java.lang.Integer dSCROutput,
			java.lang.Integer operatingMarginOutput,
			java.lang.Integer netProfitMarginOutput,
			java.lang.Integer totalScore, java.lang.Integer currentRatioOutput) {
		this.companyBureauScoreOutput = companyBureauScoreOutput;
		this.partyBureauScoreOutput = partyBureauScoreOutput;
		this.relationshipWithBankOutput = relationshipWithBankOutput;
		this.yearsOfEmploymentOutput = yearsOfEmploymentOutput;
		this.managementAssessmentOutput = managementAssessmentOutput;
		this.financialLeverageOutput = financialLeverageOutput;
		this.dSCROutput = dSCROutput;
		this.operatingMarginOutput = operatingMarginOutput;
		this.netProfitMarginOutput = netProfitMarginOutput;
		this.totalScore = totalScore;
		this.currentRatioOutput = currentRatioOutput;
	}

}