package com.temenos.infinityassist.sme;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SMERiskScoreParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer relationshipWithBank = 0;
	private java.lang.Integer yearsOfOperation = 0;
	private java.lang.Integer partyAge = 0;
	private java.lang.String partyType = null;

	private java.lang.Integer companyBureauScore = 0;

	private java.lang.Integer partyBureauScore = 0;

	public SMERiskScoreParams() {
		this.relationshipWithBank=0;
		this.yearsOfOperation=0;
		this.partyAge=0;
		this.partyType=null;
		this.companyBureauScore=0;
		this.partyBureauScore=0;
	}

	public java.lang.Integer getRelationshipWithBank() {
		return this.relationshipWithBank;
	}

	public void setRelationshipWithBank(java.lang.Integer relationshipWithBank) {
		this.relationshipWithBank = relationshipWithBank;
	}

	public java.lang.Integer getYearsOfOperation() {
		return this.yearsOfOperation;
	}

	public void setYearsOfOperation(java.lang.Integer yearsOfOperation) {
		this.yearsOfOperation = yearsOfOperation;
	}

	public java.lang.Integer getPartyAge() {
		return this.partyAge;
	}

	public void setPartyAge(java.lang.Integer partyAge) {
		this.partyAge = partyAge;
	}

	public java.lang.String getPartyType() {
		return this.partyType;
	}

	public void setPartyType(java.lang.String partyType) {
		this.partyType = partyType;
	}

	public java.lang.Integer getCompanyBureauScore() {
		return this.companyBureauScore;
	}

	public void setCompanyBureauScore(java.lang.Integer companyBureauScore) {
		this.companyBureauScore = companyBureauScore;
	}

	public java.lang.Integer getPartyBureauScore() {
		return this.partyBureauScore;
	}

	public void setPartyBureauScore(java.lang.Integer partyBureauScore) {
		this.partyBureauScore = partyBureauScore;
	}

	public SMERiskScoreParams(java.lang.Integer relationshipWithBank,
			java.lang.Integer yearsOfOperation, java.lang.Integer partyAge,
			java.lang.String partyType, java.lang.Integer companyBureauScore,
			java.lang.Integer partyBureauScore) {
		this.relationshipWithBank = relationshipWithBank;
		this.yearsOfOperation = yearsOfOperation;
		this.partyAge = partyAge;
		this.partyType = partyType;
		this.companyBureauScore = companyBureauScore;
		this.partyBureauScore = partyBureauScore;
	}

}